### ISSUE TITLE
undefined value on line 210

### ISSUE THREAD

**Issue by GerryFudd** [npm/nopt#55] opened 2015-11-12 21:57 UTC
I am the following error when I try to install a program that has nopt as a dependency:
```
    if (t && ((type.name && t.type.name) ?
                   ^
TypeError: Cannot read property 'name' of null
    at validate (/Users/davidhasenjaeger/Wirestorm/projects/costco-member-scheduling/client/node_modules/node-sass/node_modules/npmconf/node_modules/nopt/lib/nopt.js:210:20)
```

**Comment by othiym23** [comment] 2015-11-12 21:57
Closing as duplicate of #54.

**Closed by othiym23** 2015-11-12 21:57 UTC
